name: multimedia_learning_companion
description: A multimedia educational app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # Video playback
  video_player: ^2.8.1

  # Animations
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/videos/