name: multimedia_learning_companion
description: A multimedia educational app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
#custom icon
  flutter_launcher_icons: ^0.13.1
  #icons_launcher:
  flutter_native_splash: ^2.3.9
  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # Video playback
  video_player: ^2.8.1
  #audio
  just_audio: ^0.9.36 
  # Animations
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/videos/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#D32F2F"  # red to match your app
  adaptive_icon_foreground: "assets/icons/app_icon.png"


  flutter_native_splash:
    color: "#D32F2F"          # red background
    image: assets/icons/app_icon.png
    color_dark: "#B71C1C"
    image_dark: assets/icons/app_icon.png
    android_12:
      icon_background_color: "#D32F2F"
      image: assets/icons/app_icon.png